// @aegis-gen
// date: 2026-07-03
// dev: Claude Code (glm-5.2)
// change: 重建为前端本地类型的唯一手维护来源（ViewName 含 chat、统一 Record<string,unknown>）；从 protocol 生成器剥离
// @aegis-gen
// date: 2026-06-27
// dev: Claude Code (glm-5.2)
// change: 新建前端专用类型定义（非 protocol 契约类型，由前端自行维护）

// === Frontend-local types (hand-maintained; NOT from protocol/) ===
// protocol/ contract types live in ./types.ts (auto-generated by
// tooling/scripts/gen_ts_types.py). This file holds only frontend-specific
// UI / API-client types that are not part of the global protocol contract.

/** Routed views. 'chat' is the default landing view. */
export type ViewName = 'chat' | 'canvas' | 'graph' | 'monitor' | 'replay';

export type ConnectionStatus = 'connected' | 'disconnected' | 'connecting' | 'error';

export interface ApiError {
  code: string;
  message: string;
  trace_id: string;
}

export interface Session {
  id: string;
  user_id: string;
  status: 'active' | 'closed';
  context: Record<string, unknown>;
  created_at?: string;
}
